### ISSUE TITLE
Regular Windows 10 .rtf not displayed (unsupported encoding)

### ISSUE THREAD

**Issue by cmvalma** [alefragnani/vscode-language-rtf#3]
'Regular' `.rtf` files are not being displayed in vsCode. Following message ensues: 

![image](https://user-images.githubusercontent.com/44215634/57000326-5c197100-6bb3-11e9-9fa2-e5501135c403.png)

I didn't change the encoding. Clicking "Save as" shows the file is saved as type : RTF. Windows 10 Pro 1803 version (build 17314.706)

**Comment by alefragnani** [comment]
Hi @cmvalma ,

This message is shown by VS Code itself, not the extension. If you click _Do you want to open it anyway?_ the extension will work.

It appears that _Regular_ `.rtf` files are stored in unsupported text encoding. If you open it in Sublime, it shows as _hexadecimal_.  Please, fill an issue in VS Code repository, so they could take a look.

Hope this helps
